# This file was automatically generated by SWIG
package SeqManip;
require Exporter;
require DynaLoader;
@ISA = qw(Exporter DynaLoader);
package SeqManip;
bootstrap SeqManip;
package SeqManip;
@EXPORT = qw( );
1;
